---
title: "from guy"
author: "Lily Zhao"
date: "12/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



#schema
```{r}
{
  "profile": "tabular-data-package",
  "resources": [
    {
      "name": "profit-quantity-calculations",
      "path": "profit_quantity_calculations.csv",
      "profile": "tabular-data-resource",
      "schema": {
        "fields": [
          {
            "name": "document group",
            "type": "string",
            "format": "default",
            "title": "Role of individual in the value chain"
          },
          {
            "name": "document name",
            "type": "string",
            "format": "default",
            "title": "original unique ID number",
            "description": "delete from final upload"
          },
          {
            "name": "ID",
            "type": "string",
            "format": "default",
            "title": "ID "
          },
          {
            "name": "site",
            "type": "string",
            "format": "default"
          },
          {
            "name": "Country",
            "type": "string",
            "format": "default"
          },
          {
            "name": "date",
            "type": "integer",
            "format": "default",
            "description": "date at which interview was conducted",
            "title": "date-title"
          },
          {
            "name": "general role",
            "type": "string",
            "format": "default"
          },
          {
            "name": "4.2a) Who are your main supplier of octopus?  [denoted for Supplier 1]",
            "type": "string",
            "format": "default"
          },
          {
            "name": "main supplier is a fisher? (1 is yes, 0 is no)",
            "type": "boolean",
            "format": "default"
          },
          {
            "name": "location biggest? and smallest? [Supplier 1]",
            "type": "string",
            "format": "default"
          },
          {
            "name": "Gender [Supplier 1]",
            "type": "string",
            "format": "default"
          },
          {
            "name": "4.2b) how many of each of these types of supplier do you work with?)  [Supplier 1]",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Average number of suppliers (calculated from averaging 4.2b)",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "4.2c) Have you worked with them for long? [Supplier 1]",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Average number of years worked together",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "4.2d Kaz Quality [Supplier 1]",
            "type": "string",
            "format": "default"
          },
          {
            "name": "4.2d kaz Quantity [Supplier 1]",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "4.2d kaz price/kg [Supplier 1]",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "4.2d kaz price/kg [Supplier 1] EDITED in KES or TSH depending on country",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Calculated profit margin per kg in home country currency",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Calculated profit margin per kg in USD during Kazi using the conversion rates 2241.6882771832 and 103.1033080415",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "4.2d kaz week/month [Supplier 1]",
            "type": "string",
            "format": "default"
          },
          {
            "name": "Calculated average Kazi quantity in kg per month [Supplier 1] ",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Calculated average Kazi Season quantity in kg Supplier 1 (per month *6)",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Calculated average Kazi  Season quantity in kg Supplier 1 (per month *6) in metric tonnes",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Calculated per Kazi Season gross profit earned from Supplier 1. (Profit margin for Kazi from Supplier 1 in their home country currency * kg quantity from Supplier 1 per Kazi season)",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "4.2d Kusi Quality [Supplier 1]",
            "type": "string",
            "format": "default"
          },
          {
            "name": "4.2d kusi Quantity [Supplier 1]",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "4.2d kusi price/kg [Supplier 1]",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "4.2d kusi price [Supplier 1] EDITED in TNZ or KES depending on country",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "KUSI/KG CALCULATED PROFIT MARGIN FOR SUPPLIER 1 in home country currency : average kusi selling price/kg- average buying price/kg",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "4.2d kusi week/month [Supplier 1]",
            "type": "string",
            "format": "default"
          },
          {
            "name": "Calculated average Kusi quantity in kg per month [Supplier 1]",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Calculated average Kusi Season quantity in kg [Supplier 1] (per month *6)",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Calculated average Kusi Season quantity in kg [Supplier 1] (per month *6) in metric tonnes",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Calculated PER KUSI Season GROSS PROFIT EARNED FROM SUPPLIER 1: (PROFIT MARGIN/KG*KG QUANTITY PER KUSI)",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "4.2a) Who are your 2nd main supplier of octopus?  *Denoted as supplier 2",
            "type": "any",
            "format": "default"
          },
          {
            "name": "2nd main supplier edited",
            "type": "string",
            "format": "default"
          },
          {
            "name": "For supplier 2: location biggest? and smallest?",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2: Gender",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2:  4.2b) how many of each of these types of supplier do you work with?) ",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Total number of fishers supplying interviewee (calculated from supplier 1 and 2)",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Total number of traders supplying interviewee (calculated supplier 1 and 2)",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Total number of suppliers main and secondary (as calculated)",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "For supplier 2: 4.2c) Have you worked with them for long?",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2:  4.2d )Kaz Quality",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2: 4.2d kazi Quantity",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2: 4.2d) kaz price/kg",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2: 4.2d) kaz price/kg EDITED",
            "type": "any",
            "format": "default"
          },
          {
            "name": "KAZI/KG CALCULATED PROFIT MARGIN FOR SUPPLIER 2: in home country currency  (average kazi selling price/kg- average buying price/kg)",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2: 4.2d) kaz week/month",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Calculated average Kazi quantity in kg per month [Supplier 2]",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Calculated average Kazi  Season quantity in kg  [Supplier 2] *6 months",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Calculated average Kazi Season quantity in kg  [Supplier 2] *6 months in metric tonnes",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Calculated PER KAZI Season GROSS PROFIT EARNED FROM SUPPLIER 2: (PROFIT MARGIN/KG*KG QUANTITY PER KAZI",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2: 4.2d) Kusi Quality",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2: 4.2d) kusi Quantity",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2:  4.2d) kusi price/kg",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2:  4.2d) kusi price/kg EDITED",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Kusi/KG CALCULATED PROFIT MARGIN FOR SUPPLIER 2 in home country currency : average kusi selling price/kg- average buying price/kg",
            "type": "any",
            "format": "default"
          },
          {
            "name": "For supplier 2:  4.2d) kusi week/month",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Calculated average Kusi quantity in kg per month [Supplier 2]",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Calculated average Kusi Season quantity in kg per KUSI [Supplier 2] *6 months",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Calculated average Kusi Season quantity in kg per month [Supplier 2] *6 months in metric tonnes",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Calculated PER KUSI Season GROSS PROFIT EARNED FROM SUPPLIER 2: (PROFIT MARGIN/KG*KG QUANTITY PER KUSI)",
            "type": "any",
            "format": "default"
          },
          {
            "name": "Calculated TOTAL PER KAZI Season GROSS PROFIT in home country currency EARNED FROM SUPPLIER 1& 2",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Calculated TOTAL PER KUSI Season GROSS PROFIT in home country currency EARNED FROM SUPPLIER 1& 2",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "TOTAL KUSI Season GROSS PROFIT IS WHAT PROPORTION OF KAZI Season GROSS PROFIT (total kusi gross profit/total kazi gross profit)",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "CALCULATED YEARLY GROSS PROFIT (TOTAL KAZI SEASON GROSS PROFIT +TOTAL KUSI SEASON GROSS PROFIT) in TZS or KES depending on country",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "Calculated Kazi season gross profit USD",
            "type": "number",
            "format": "default"
          },
          {
            "name": "Calculated Kusi season gross profit USD",
            "type": "string",
            "format": "default"
          },
          {
            "name": "CALCULATED YEARLY GROSS PROFIT (TOTAL KAZI SEASON GROSS PROFIT +TOTAL KUSI SEASON GROSS PROFIT) in USD using SEPT conversion rates of 2241.6882771832 and 103.1033080415 ",
            "type": "number",
            "format": "default"
          },
          {
            "name": "CALCULATED YEARLY QUANTITY TRADED BY RESPONDENT: (Quantity from supplier 1 and 2/Kazi +Quantity supplier 1 and 2/Kusi) in metric tonnes",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "5.1a main buyers-domestic",
            "type": "string",
            "format": "default"
          },
          {
            "name": "5.1b octopus product type wanted (** for interviewees this is all fresh) There is a dry local market but at different locations.- none going for export.  We heard of it and observed but did not get into it (the mzungu initial starting price is 20,000 TSH per dry octopus)",
            "type": "string",
            "format": "default"
          },
          {
            "name": "5.1c kaz quality",
            "type": "string",
            "format": "default"
          },
          {
            "name": "5.1c kaz quantity",
            "type": "any",
            "format": "default"
          },
          {
            "name": "5.1c kaz week/month",
            "type": "any",
            "format": "default"
          },
          {
            "name": "5.1c kaz price/kg",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "5.1c Kazi Buying price/kg in home country currency EDITED (used for profit margin calculations)",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "5.1c kusi quality",
            "type": "string",
            "format": "default"
          },
          {
            "name": "5.1c kusi price/kg",
            "type": "integer",
            "format": "default"
          },
          {
            "name": "5.1c kusi Buying price/kg in home country currency EDITED (used for profit margin calculations)",
            "type": "integer",
            "format": "default"
          }
        ]
      },
      "title": "profit-quantity-title",
      "format": "csv"
    }
  ],
  "keywords": [
    "octopus",
    "trade",
    "Mozambique",
    "Kenya",
    "Tanzania",
    "middlemen"
  ],
  "name": "east-africa-octopus-trade-data",
  "title": "East Africa Octopus Trade Data",
  "description": "Value Chain data for octopus collected in Tanzania and Kenya in 2017",
  "contributors": [
    {
      "title": "Lily Z. Zhao et al. ",
      "role": "author"
    }
  ],
  "licenses": [
    {
      "name": "CC0-1.0",
      "title": "CC0 1.0",
      "path": "https://creativecommons.org/publicdomain/zero/1.0/"
    }
  ]
}

#Error: unexpected ',' in:
"{
  "profile": "tabular-data-package","
```

